[package]
name = "wasm-othello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.8.5"
js-sys = "0.3.60"
wee_alloc = "0.4.5"
wasm-bindgen = "0.2.83"
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2", features = ["js"] }
